export const LOAD_PATIENT = 'LOAD_PATIENT';
export const REGISTER_PATIENT = 'REGISTER_PATIENT';
export const LOGIN_PATIENT = 'LOGIN_PATIENT';
export const CURRENT_PATIENT = 'CURRENT_PATIENT';
export const LOGOUT_PATIENT = 'LOGOUT_PATIENT';
export const FAIL_PATIENT = 'FAIL_PATIENT';

